version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      args:
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
        REDIRECT_URI: ${REDIRECT_URI}
        SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
